apiVersion: batch/v1
kind: Job
metadata:
  generation: 1
  labels:
    app: crlite-rebuild
  name: crlite-rebuild
  namespace: default
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crlite-rebuild
    spec:
      containers:
      - name: crlite-rebuild
        image: gcr.io/crlite-beta/crlite:0.1-rebuild
        envFrom:
        - configMapRef:
            name: crlite-config
        imagePullPolicy: Always
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 120
