- repo: git://github.com/dnephin/pre-commit-golang
  sha: HEAD
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: validate-toml
- repo: local
  hooks:
    - id: go-unit-tests
      name: Go unit tests
      language: script
      entry: hooks/go-unit-tests.sh
      files: '\.go$'
