language: go

script:
  - export GOROOT=$(go env GOROOT)
  - cd go
  - if [ -n "$(gofmt -l .)" ]; then
      echo "Go code is not formatted:"; gofmt -d .; exit 1;
    fi
  - go test ./...
  - go test -race -short ./...
