apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: crlite-fetch
  name: crlite-fetch
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: crlite-fetch
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crlite-fetch
    spec:
      containers:
      - env:
        - name: logList
          valueFrom:
            configMapKeyRef:
              key: logList
              name: crlite-config
        - name: firestoreProjectId
          valueFrom:
            configMapKeyRef:
              key: firestoreProjectId
              name: crlite-config
        - name: credentials_data
          valueFrom:
            configMapKeyRef:
              key: credentials_data
              name: crlite-config
        - name: numThreads
          valueFrom:
            configMapKeyRef:
              key: numThreads
              name: crlite-config
        - name: cacheSize
          valueFrom:
            configMapKeyRef:
              key: cacheSize
              name: crlite-config
        - name: runForever
          valueFrom:
            configMapKeyRef:
              key: runForever
              name: crlite-config
        - name: redisHost
          valueFrom:
            configMapKeyRef:
              key: redisHost
              name: crlite-config
        - name: outputRefreshPeriod
          valueFrom:
            configMapKeyRef:
              key: outputRefreshPeriod
              name: crlite-config
        - name: statsRefreshPeriod
          valueFrom:
            configMapKeyRef:
              key: statsRefreshPeriod
              name: crlite-config
        - name: savePeriod
          valueFrom:
            configMapKeyRef:
              key: savePeriod
              name: crlite-config
        - name: pollingDelayMean
          valueFrom:
            configMapKeyRef:
              key: pollingDelayMean
              name: crlite-config
        - name: pollingDelayStdDev
          valueFrom:
            configMapKeyRef:
              key: pollingDelayStdDev
              name: crlite-config
        image: gcr.io/crlite-beta/crlite:0.1-fetch
        name: crlite-fetch
        imagePullPolicy: Always
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 120
status:
  availableReplicas: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
